repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black .
        pass_filenames: false
        language: system
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
      - id: system
        name: autoflake
        entry: poetry run autoflake -r --in-place --remove-unused-variables .
        pass_filenames: false
        language: system
